input:
    col_paciente: "ID_PACIENTE"
    col_colheita: "DATA_COLHEITA"
    col_parametro: "ID_PARAMETRO"
    col_episodio: "DATA_ADMISSAO_UCI"
    configs_base: "./configs"
    logs_base: "./logs"

schema:
    tbl_colheita: "colheita"
    tbl_resultado: "resultado"
    tbl_parametro: "parametro"
    tbl_merged_ids_params: "params_merged"
    tbl_cat_values: "filtered_cat_values"
    tbl_transformed_filtered_values: "transformed_filtered_values"
    tbl_patient_min_max_result: "patient_min_max_result"
    tbl_long_therapy: "therapy_long"
    tbl_cross_sec_therapy: "therapy_cross_sec"
    tbl_drugs: "drugs"
    tbl_patient_data_result_num: "patient_data_result_num"
    tbl_patient_data_result_cat: "patient_data_result_cat"
    tbl_cols: 'cols'


    tbl_episodio: "episodio"
    tbl_processo: "processo"
    tbl_login: "login"
    tbl_vmi: "vmi"
    tbl_ecmo: "ecmo"
    tbl_comorb: "comorbidade"

    v_filtered: "v_filtered_values"
    v_agreg_cat_values: "v_agreg_cat_values"
    v_agreg_num_values: "v_agreg_num_values"
    v_patient_data: "v_patient_data"
    v_patient_data_min_max_result: "v_patient_data_min_max_result"
    v_patient_data_min_max_result_cat: "v_patient_data_min_max_result_cat"
    v_params_merged: "v_params_merged"

    